version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
        bash -c "composer install && php artisan migrate && php artisan passport:client --personal && php-fpm"
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
    - "8000:8000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  db:
    image: mysql:8.0.36
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
